### ISSUE TITLE
CFEclipse and Eclipse Oxygen - Can't get it to work --- The Impossible Dream?

### ISSUE THREAD

**Issue by AllenGraetz** [cfeclipse/cfeclipse#103]
Good Afternoon,

Having been out of the CFEclipse world for a few years, I'm not sure where things stand.  It looks like CFEclipse is sorta dead?  Yes?  No?

I am unable to install CFEclipse and get it running with Eclipse Oxygen.  I'm getting the below error when trying to install CFEclipse for Eclipse Oxygen ( v.4.7.0; Build id: 20170620-1800 ).   I am able to hit the URI in my browser and grab the jar file.  

Any ideas of what is causing this issue?  I've tried both the update and update-dev for installing the plugin but get the same error.

Thank you.

~Allen

------

An error occurred while collecting items to be installed

session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).

Unable to read repository at http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/updates/wdt/oxygen_comp/repository/plugins/com.ibm.websphere.v9.core_1.100.1.v20171214_0201.jar.

**Comment by bardware** [comment]
What eclipse do you have installed? Some full featured version? I usually start with the [Platform Runtime Binary](http://download.eclipse.org/eclipse/downloads/drops4/R-4.7.2-201711300510/)

**Comment by am2605** [comment]
Closing issue due to age.  

The version at http://cfeclipse.org/update-nightly should install with the latest eclipse version.  Please open a new issue if this is not the case.
