### ISSUE TITLE
Security Warning - unsigned content

### ISSUE THREAD

**Issue by wenima** [cfeclipse/cfeclipse#105]
Following the installation instructions, I'm getting the following warning.

![image](https://user-images.githubusercontent.com/22766301/39199807-3fd5bdf2-479f-11e8-9217-34ec2c47e75e.png)

**Comment by am2605** [comment]
I believe this is because we are not signing the releases.  My experience is that this is the case for quite a few of the eclipse plugins we use, but I do agree it would be a useful thing to look into, to see what's involved to get this sorted out.
