### ISSUE TITLE
Oxygen and CFEclipse-Editor-CFML Colours not correct

### ISSUE THREAD

**Issue by tvanderlois** [cfeclipse/cfeclipse#113]
CFML comments are green, scopes are same color as cfml tag... modifying colors doesn't seem to work at all. 

![image](https://user-images.githubusercontent.com/9574425/41875761-808d9dce-7891-11e8-85ed-4c5eaf9385ca.png)

![image](https://user-images.githubusercontent.com/9574425/41875856-c771dbd8-7891-11e8-9791-20dfc674d88f.png)

![image](https://user-images.githubusercontent.com/9574425/41875578-e6381eb6-7890-11e8-828c-40e10bb09b50.png)

**Comment by am2605** [comment]
The build in update-dev uses TextMate for its coloring.  This gets its colors from a css file and ignores the colors in the settings.  

I've been discussing with @denuno the possibility of putting out a new stable build which backs this out until we can spend a bit more time fixing a few other issues around the TextMate stuff.

**Comment by am2605** [comment]
Fixed in upcoming build 1.5.3
