### ISSUE TITLE
won't work any longer

### ISSUE THREAD

**Issue by dtxl** [cfeclipse/cfeclipse#119]
With the latest version of Eclipse trying to install it gives "The following solutions are not compatible with this version of Eclipse: CFEclipse".

Thanks.

**Comment by bardware** [comment]
What is the latest version of eclipse as time of your writing?
How did you try to install `CFEclipse`?

**Comment by aousterhout** [comment]
I suggest you follow the instructions here in case you didn't :  https://github.com/cfeclipse/cfeclipse/wiki/Installing-CFEclipse

Andy

**Comment by dtxl** [comment]
Since CFEclipse is not available at the Eclipse Marketplace I went to http://cfeclipse.org/download/, clicked on Eclipse Marketplace and followed the instruction "Drag to your running Eclipse workspace. Requires Eclipse Marketplace Client". Then the error message is "The following solutions are not compatible with this version of Eclipse: CFEclipse".

**Comment by bardware** [comment]
I never got used to using the Marketplace. I tried what you describe and ended up with the same error. When I, however, create an update site in eclipse pointing to http://cfeclipse.org/update-dev/, I can install CFEclipse in eclipse 4.11

**Comment by dtxl** [comment]
That worked. Thank you very much!
