### ISSUE TITLE
cf10 dictionary for CfEclipse Plugin

### ISSUE THREAD

**Issue by NaranRaj** [cfeclipse/cfeclipse#12]
I updated CfEclipse plugin to 1.4.5.201112121854. But the CFML Language version 10 is missing. I want to create application using Coldfusion 10. Kindly do the needful.
![image](https://f.cloud.github.com/assets/4427534/603191/33b6d3ce-ccb8-11e2-98a7-d5d7c9778a33.png)

**Comment by denuno** [comment]
#50 closes this too
