### ISSUE TITLE
Download CFEclipse package for offline installation

### ISSUE THREAD

**Issue by DylanNgo** [cfeclipse/cfeclipse#120]
I'm trying to download the CFEclipse package for offline installation to my private network that has no connection to internet.  I saw a link at http://cfeclipse.org/update site to download http://cfeclipse.org/update/cfeupdatesite.zip but this doesn't work.  

Can you show or point me to the right direction of where to get this package for offline installation?

Thanks
Dylan

**Comment by am2605** [comment]
I'm a bit doubful this will work, because the current builds depend on some stuff hosted external to cfeclipse (cflint for example).  

But in case it does, I created a zip of the update-dev site at http://cfeclipse.org/update-dev/cfeupdatesite.zip.
