### ISSUE TITLE
1.5.3 cannot be installed from Marketplace

### ISSUE THREAD

**Issue by amyers735** [cfeclipse/cfeclipse#127]
Appears to be related to cflint 1.3.0 not being visible to the marketplace installer.  I am investigating how to resolve this

**Comment by am2605** [comment]
See discussion at https://www.eclipse.org/forums/index.php?t=rview&goto=1815272#msg_1815272

**Comment by pdinc-oss** [comment]
as far as I can tell, eclipse seems to think that the update site [http://cfeclipse.org/cflint/update/] does not have http://cfeclipse.org/cflint/update/plugins/org.cfeclipse.cflint_1.3.0.jar , but only has http://cfeclipse.org/cflint/update/plugins/org.cfeclipse.cflint_1.0.10.201909230024.jar

is the http://cfeclipse.org/cflint/update/artifacts.jar or http://cfeclipse.org/cflint/update/content.jar corrupt or not updated?

**Comment by pdinc-oss** [comment]
manually downloading and installing the http://cfeclipse.org/cflint/update/plugins/org.cfeclipse.cflint_1.3.0.jar mitigates the issue.
