### ISSUE TITLE
Cannot install CFEclipse on Oxygen

### ISSUE THREAD

**Issue by timpenn** [cfeclipse/cfeclipse#128]
Running Eclipse Oxygen.3a Realease 4.7.3a

When I try and install CFEclipse I get the following error
Cannot complete the install because one or more required items could not be found.
  Software being installed: CFEclipse (including Frameworks) 1.5.3 (org.cfeclipse.cfml.feature.feature.group 1.5.3)
  Missing requirement: CFML Plug-in 1.5.3 (org.cfeclipse.cfml 1.5.3) requires 'bundle org.cfeclipse.cflint 1.3.0' but it could not be found
  Cannot satisfy dependency:
    From: CFEclipse (including Frameworks) 1.5.3 (org.cfeclipse.cfml.feature.feature.group 1.5.3)
    To: org.cfeclipse.cfml [1.5.3]

I am assuming this is the problem  Missing requirement: CFML Plug-in 1.5.3 (org.cfeclipse.cfml 1.5.3) requires 'bundle org.cfeclipse.cflint 1.3.0' but it could not be found

When I try to install cflint  I get the following error :~

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.cfeclipse.cflint,1.0.10.201909230024

Is there a solution to this

**Comment by pdinc-oss** [comment]
as far as I can tell, eclipse seems to think that the update site [http://cfeclipse.org/cflint/update/] does not have http://cfeclipse.org/cflint/update/plugins/org.cfeclipse.cflint_1.3.0.jar , but only has http://cfeclipse.org/cflint/update/plugins/org.cfeclipse.cflint_1.0.10.201909230024.jar

is the http://cfeclipse.org/cflint/update/artifacts.jar or http://cfeclipse.org/cflint/update/content.jar corrupt or not updated?

manually downloading and installing the http://cfeclipse.org/cflint/update/plugins/org.cfeclipse.cflint_1.3.0.jar mitigates the issue.
