### ISSUE TITLE
Log4j

### ISSUE THREAD

**Issue by hammo** [cfeclipse/cfeclipse#133]
Any advice in moving from the unsupported version of log4j-1.2.17 to 2.17?  My organization is forcing this.

**Comment by hammo** [comment]
They finally forced a delete of log4j so cfeclipse is dead for me
Plug-in org.cfeclipse.cfml was unable to load class org.cfeclipse.cfml.editors.CFMLEditor.
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.PropertyConfigurator cannot be found by org.cfeclipse.cfml_1.5.2.201612262348

**Comment by gmorphis** [comment]
Same for me, I'm being asked to remove the file log4j-1.2.17 or "update it to 2.16.0" by August 31. Seems like it would be easy to upgrade the version cfeclipse is using but I'm not an expert on that. If it ever gets updated I'll go back. But I guess for now I'll be using VSCode.

**Comment by hammo** [comment]
I switched to CF Builder, but turns out it has a similar problem (embedded
in a Jar file)
