### ISSUE TITLE
cfeclipse breaks Outline view

### ISSUE THREAD

**Issue by sekanitembo** [cfeclipse/cfeclipse#18]
Specs:
Mac OS X 10.9 Mavericks
3.2 GHz Intel Core i5
8 GB DDR3
Eclipse Platform:
Version: Kepler 4.3.1.v20130911-1000
Build id: M20130911-1000
CFEclipse:
CF Frameworks Plugin v1.0.3.3
CFEclipseCall v1.1.0.3
CFML Plug-in v1.4.4.201012220425
Templates Fragment v1.0.0.3

If using the outline view and multiple files, eventually switching between them no longer functions. Files which are not open in the editor are shown in the outline view (i.e. "Link with Editor" function of Outline view doesn't work")

**Comment by denuno** [comment]
Seems to be fixed.
