### ISSUE TITLE
http://mxunit.org/update/plugins/org.mxunit.eclipseplugin_1.4.5.201211261830.jar is empty

### ISSUE THREAD

**Issue by gfbj** [cfeclipse/cfeclipse#30]
not much help when you don't have control of outside resources. I have Kepler 4.3.2 installed from 5/9/2014, tried both /update and /update-dev to no avail. Both stall looking for http://mxunit.org/update/plugins/org.mxunit.eclipseplugin_1.4.5.201211261830.jar

An error occurred while collecting items to be installed
session context was:(profile=epp.package.standard, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://mxunit.org/update/plugins/org.mxunit.eclipseplugin_1.4.5.201211261830.jar.
Read timed out

**Comment by denuno** [comment]
Should be fixed now.
