### ISSUE TITLE
NoViableAltException Parser error

### ISSUE THREAD

**Issue by GadgetMan0101** [cfeclipse/cfeclipse#34]
After installing the new 1.4.6 cfeclipse plugin, one of my *.cfc files now lists an error of type 
```
"CFEclipse parser problem" at line 1 as:
    null < 158org.antlr.runtime.NoViableAltException
``` 
The outline view shows ```"Error creating outline: []"``` and the Methods view only gives the file name and nothing more. 

Most of my *.cfc files seem to parse just fine, however, this error occurs on at least 2 of them.

I've Installed a new version of eclipse and created a new workspace to insure no other plugins were interfering.

Eclipse version: Kepler Service Release 2, Build Id 20140224-0627
CFEclipse version:   CFEclipse (including MXUnit and Frameworks)	1.4.6.R201403180646	
Java version: java.runtime.version=1.7.0-b147
Operating System: Window 7 Professional

I was able to create a simple cfm that duplicates the error.
```coldfusion
<!--- Random Comment --->
<cfscript>
    myObj = createObject("component", "cfc.testCfc");
    function someFunction() {

    }
</cfscript>
```
Removing the comment, the createObject line, or the function will remove the error.

**Comment by Alandar** [comment]
Simply removing the "component" text will remove the error, so ugly workaround can be to change "component" to something like "comp"&"onent"
But this is really annoying... Hopefully it won't take another 2 years for next cfeclipse update

**Comment by denuno** [comment]
Seems to be fixed in the latest dev version.
