### ISSUE TITLE
installation impossible  Missing requirement: CFML Plug-in ...

### ISSUE THREAD

**Issue by pilere** [cfeclipse/cfeclipse#40]
I try to install CFeclipse on juno, following thoses instructions https://github.com/cfeclipse/cfeclipse/wiki/Installing-CFEclipse ,but I got this error :

Cannot complete the install because one or more required items could not be found.
  Software being installed: CFEclipse (including MXUnit and Frameworks) 1.4.6.R201403180646 (org.cfeclipse.cfml.feature.feature.group 1.4.6.R201403180646)
  Missing requirement: CFML Plug-in 1.4.6.R201403180646 (org.cfeclipse.cfml 1.4.6.R201403180646) requires 'bundle org.eclipse.search [3.9.0,4.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: CFEclipse (including MXUnit and Frameworks) 1.4.6.R201403180646 (org.cfeclipse.cfml.feature.feature.group 1.4.6.R201403180646)
    To: org.cfeclipse.cfml.frameworks [1.0.3.4]
  Cannot satisfy dependency:

whats wrong ???

Stéphane

**Comment by OfficeFIeld** [comment]
Really...Worked like a charm. Just Signed UP with GitHub to give you a thumbs UP. Thanks

**Comment by nukleos** [comment]
Well, the bypass given does work - if you install the "preview" version. But the core problem still remains, as I just experienced while trying to install the "stable" version in Eclipse 4.2. How can this ticket be reopened? And who can solve the error?
