### ISSUE TITLE
Better handling of default location for dictionaries

### ISSUE THREAD

**Issue by denuno** [cfeclipse/cfeclipse#47]
We either need to use a different default location for the dictionaries or make the code smarter so that it doesn't look in the previous version's plugin folder, which may not exist after an upgrade.  I think we'll have to do the later to make upgrading possible anyway, but we don't want to wipe/lose the any customized dictionaries.  Maybe user.home, but then we need to handle any changes to the dictionary format.  Hrm... this is needed even for CFE 2.0, and should be in handled in cfml.parsing/cfml.dictionaries.

**Comment by cybersonic** [comment]
One plan a while ago was to make dictionaries as features so you could just add them in as you go and they could have their own projects and lifecycles. Not sure if that is what you mean with this ticket?

**Comment by denuno** [comment]
Yeah, we've got to think of something that'll work better than that, and not be tied to Eclipse, instead being tied to cfml.dictionaries, so folks can get the benefits in CFLint and whatnot as well.

There's some talk on #documentation in slack about using cfdocs to gen dictionaries, but right now there isn't enough data in the schema to use it for editors and whatnot ("optionally required" arguments, engine type, engine version, etc.), but ideally I'd like to leverage that, as we could pull in user comments and examples and whatnot too, which would be P to the I to the M to the P.

**Comment by denuno** [comment]
The solution needs to be flexible enough to pull in user-supplied dictionaries as well, and it would be neat to be able to use the same machinery for pulling in/sharing code templates (which are currently a feature in themselves, thus separately updateable and whatnot).
