### ISSUE TITLE
add initial CFLint integration

### ISSUE THREAD

**Issue by denuno** [cfeclipse/cfeclipse#49]
It would be pretty nifty to have CFLint integrated, with output put in the "problems" view as well as markers on the source files where the problems appear.

It should be a "builder" so processing can happen in the background, and be done on the whole project if a full build is called.

The user should be able to turn it on and off per project, with the default being whatever is set in the main CFE preferences.

**Comment by cybersonic** [comment]
Opened and closed. Did you do code for this? Is there a related commit?

**Comment by denuno** [comment]
Yep, one or two commits. (One to add it, and another to update it so it hopefully doesn't explode someone's workstation right after install.  It's also disabled by default now, for now.)

There's a global CFE "CFLint" preference page for enabling it, and then a project "CFLint" preference page for enabling it per project.  Eventually there will be other configuration options. :-P

It should be in the update-dev update site, theoretically, if folks want to try it.

**Comment by SebastianZ** [comment]
> Yep, one or two commits. (One to add it, and another to update it so it hopefully doesn't explode someone's workstation right after install. It's also disabled by default now, for now.)

Shouldn't those commits be listed here:

https://github.com/cfeclipse/cfeclipse/commits/master

I suggest you mention the related issue number within your commits, so they are shown within the issue.

Sebastian

**Comment by denuno** [comment]
The action is happening here:
https://github.com/cfeclipse/cfeclipse/commits/develop

Which gets built to this update site:
http://cfeclipse.org/update-dev

I wasn't adding the # before the ticket number, or the commits would have been linked here, d'oh!

**Comment by SebastianZ** [comment]
Ah, I see. Thanks for the info!
So for reference, the related commits are 8258cc40dc, a17f618ed6 and 003b36049b.

Sebastian

**Comment by denuno** [comment]
Thanks for posting the commit refs!

I'll be switching to just merging PRs from my own repo eventually, so the history will be a little cleaner.  

I've also been using these commits to verify the new builds are working as expected, creating valid update sites and whatnot.
