### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by sgrundy** [cfeclipse/cfeclipse#55]
Hey guys, you do a great job and I use CFEclipse all the time so I'd like to make a donation, but the WePay link has been broken for a long time.  Are you still looking for donations?  If so, how should it be done?

**Comment by denuno** [comment]
Donations are always welcome!

I'll see about updating the WePay stuff, so we can have an account for things like attending conferences.  I'll close this ticket when I've done that.

For things like coffee, beer, and pizza, my PayPal addy is valliantster@gmail.com.  =]
