### ISSUE TITLE
F1 cfdocs.org

### ISSUE THREAD

**Issue by noatak** [cfeclipse/cfeclipse#56]
If i hit F1 in cfeclipse 1.5.0 still points to cfquickdocs.com, which is not working. I can't find the configuration, where i can change help function to use cfdocs.org.

**Comment by denuno** [comment]
That's probably being picked up by your preferences.  I just verified that the default external help URL is cfdocs.org.  To change the preference, go to : window > preferences > cfeclipse : External Help Documentation and set it to the URL you'd like to use.

**Comment by noatak** [comment]
Thank you very much, i had to delete http://cfdocs.org in window > preferences > cfeclipse : External Help Documentation save it and then enter http://cfdocs.org again. Now it is working as expected.
