### ISSUE TITLE
Module in CFscript not recognized (CFScript Parsing)

### ISSUE THREAD

**Issue by ppaquette** [cfeclipse/cfeclipse#6]
The following code triggers a parsing error:

module
        name="customTagName"
        returnVariable="variableName"
;

The module is the CFScript equivalent of cf_module and is used to call a custom tag (in Railo)

Documentation here: http://wiki.getrailo.org/wiki/TAG:CFMODULE
Example here: http://stackoverflow.com/questions/9215424/can-i-call-a-custom-tag-in-cfscript

**Comment by denuno** [comment]
This was probably fixed in 1.5.0, tho I just tested it on 1.5.1 (dev), so...
