### ISSUE TITLE
Dependency on org.eclipse.e4.ui.workbench ?

### ISSUE THREAD

**Issue by boughtonp** [cfeclipse/cfeclipse#60]
In org.cfeclipse.cfml there is a dependency on org.eclipse.e4.ui.workbench which stops it from working with earlier versions of Eclipse.

Adding `;resolution:=optional` allows it to build/run in Kepler and installs to Juno.

Are there going to be any unexpected side-effects of making this optional?
(I'm sticking with those versions because Luna/Mars/Neon all have broken editor tiling.)

**Comment by denuno** [comment]
Well, I added it.  We'll get folks to test the dev version and see if it breaks anything for them.  It shouldn't, as I don't think we're using any of the e4 stuff... anyhow tho, CI should be building this and a bunch of other fixes into the update-dev update site, give it a go and let me know if it's all kosher.

**Comment by boughtonp** [comment]
So last time I did a local update site and built/installed an updated Snippets project, which now causes a conflict if I try installing from the update-dev site. I'll try uninstalling that at some point, but in the meantime I've pulled the latest develop branch and built/updated that and it's running ok.

**Comment by denuno** [comment]
Nice!  The dev build has it in there as of yesterday, we'll see if anyone runs into any issues relating to that change pretty soon.  I know a couple of people have already updated, so far no problems with the change.
