### ISSUE TITLE
Parser doesn't support "does not contain" operator

### ISSUE THREAD

**Issue by boughtonp** [cfeclipse/cfeclipse#61]
Getting `no viable alternative at input 'if(len(cgi.http_referer)and"/"&cgi.http_referer&"/"does not contain'` for this simplified CFC:

```
<cfcomponent output=false >
	<cfsetting enablecfoutputonly=true showdebugoutput=false />

	<cffunction name="onSessionStart" returntype="void" output=false >
		<cfscript>

			if (len(cgi.HTTP_REFERER) and "/"&cgi.HTTP_REFERER&"/" does not contain "/"&cgi.HTTP_HOST&"/"){

				}
		</cfscript>
	</cffunction>

</cfscript>
</cfcomponent>
```

Also, the error is highlighed earlier in the file - it's at the cffunction line above, but add a comment above the cfcomponent and it moves up to the cfsetting. Copy & paste the cfsetting line a handful of times and it stays on the first one, remove the comment and it moves to the third cfsetting line

**Comment by denuno** [comment]
I still have to work on the markers... the error is triggered on the next thing that isn't expected, so the marker needs to be on the thing before the thing which causes the error, but that's not always the case... anyways, we should have a separate ticket for incorrect error marker positions I reckon.

**Comment by boughtonp** [comment]
I've raised #66 for the that.

For issues that are parser issues, should I raise those direct on cfml.parsing project?

**Comment by denuno** [comment]
What you're doing is perfect, thanks!
