### ISSUE TITLE
No viable alternative for escaped hashes

### ISSUE THREAD

**Issue by boughtonp** [cfeclipse/cfeclipse#63]
Error: `no viable alternative at input ''#';'`

```
<cfscript>
	EscapedHash = '##';
</cfscript>
```

**Comment by boughtonp** [comment]
Probably same or similar issue for quotes: `varname = 'stuff here ''#x.func()#'' and here';`
Error: `mismatched input ''' expecting {CONTAINS, GT, GTE, LTE, LT, EQ, NEQ, OR, EQV, XOR, AND, '++', '--', ';', '||', '&&', '?'}`

**Comment by denuno** [comment]
This looks to be fixed in the latest dev release.
