### ISSUE TITLE
incorrect error marker positions

### ISSUE THREAD

**Issue by boughtonp** [cfeclipse/cfeclipse#66]
As described in #61 

> I still have to work on the markers... the error is triggered on the next thing that isn't expected, so the marker needs to be on the thing before the thing which causes the error, but that's not always the case

If it's not possible/easy, would be handy to have the tooltip contain something line "parser error between lines X and Y" or "[X..Y] parser error" - where X..Y are where the error is between?

**Comment by denuno** [comment]
I'm 90% certain that with the right logic we can get the correct line, which is basically what we'd need to do to get the correct range anyway, but if not, I like the range idea, since at least it's clear that it's a general location.
