### ISSUE TITLE
class org.cfeclipse.cfml.editors.CFDocumentSetupParticipant' must not install a default partitioner

### ISSUE THREAD

**Issue by bardware** [cfeclipse/cfeclipse#68]
I keep seeing the message:

```
'class org.cfeclipse.cfml.editors.CFDocumentSetupParticipant' must not install a default partitioner.
    When a 'org.eclipse.core.filebuffers.documentSetup' extension wants to install partitioning on the document, it must use the 'org.eclipse.jface.text.IDocumentExtension3' API and use a unique partitioning. 
```

in the Eclipse `Error Log`. I guess Eclipse changed something CFEclipse does not reflect.

**Comment by boughtonp** [comment]
Got any more details?

Searching for the error returns a message on the mailing list from 2012:

  https://groups.google.com/forum/#!topic/cfeclipse-users/KeN0A763DhE

That one mentions it's stopping a file from opening...

**Comment by denuno** [comment]
I see that intermittently.  I'm not sure where it's coming from, and it's never stopped CFE from working.  I'll check it out more when I get a chance tho.

**Comment by bardware** [comment]
Other textbox says: `An exception stack trace is not available.`
