### ISSUE TITLE
Multiple errors when using the word "component" followed by {

### ISSUE THREAD

**Issue by LucasKell** [cfeclipse/cfeclipse#71]
I've noticed a few cfm files have been showing error markers the whole way down the page, most stating the error: "There seems to be a missing semicolon; here bud". It seems that when using the word "component" in some circumstances this occurs. One example is if you have a html style tag and you call a class .component then place the opening {, this seems to cause the error. The only way to get around this is to not use the word component.

This can also be replicated by having this in a string, for example: `<cfset test = "component {"/>` will cause it, as will putting characters between the word component and the {

Eclipse - Version: Kepler Service Release 2 Build id: 20140224-0627
CFEclipse - Version 1.5.1.201605220951
Java - Version 1.8.0_45
Operating System: Windows 7 Professional

**Comment by denuno** [comment]
I think this is fixed with 1.5.3, feel free to reopen if not.
