### ISSUE TITLE
Cannot install 1.5.2 or 1.5.3 due to missing dependency 'org.mxunit.eclipseplugin.feature.feature.group 1.5.0'

### ISSUE THREAD

**Issue by SebastianZ** [cfeclipse/cfeclipse#77]
Trying to install CFEclipse 1.5.2 or 1.5.3 on Eclipse Neon.2 4.6.2 I get the following dependency error:

> Cannot complete the install because one or more required items could not be found.
>   Software being installed: CFEclipse (including MXUnit and Frameworks) 1.5.2.201612262348 (org.cfeclipse.cfml.feature.feature.group 1.5.2.201612262348)
>   Missing requirement: CFEclipse (including MXUnit and Frameworks) 1.5.2.201612262348 (org.cfeclipse.cfml.feature.feature.group 1.5.2.201612262348) requires 'org.mxunit.eclipseplugin.feature.feature.group 1.5.0' but it could not be found

As solution it offers the 1.5.0 release from April 2016.

Sebastian

**Comment by denuno** [comment]
Try installing from the dev update site, which should be fixed, and feel free to reopen if not!

**Comment by SebastianZ** [comment]
Just updated to dev version and it worked like a charm! Thanks and a Happy New Year!

Sebastian

**Comment by MFernstrom** [comment]
Same issue on Oxygen.2 Release (4.7.2), except it doesn't offer any solution.

So how do you install from the dev update site?
