### ISSUE TITLE
CFEclipse not compatible with Eclipse Neon

### ISSUE THREAD

**Issue by adeptdeveloper** [cfeclipse/cfeclipse#81]
I recently installed Eclipse Neon and my editor won't open for cfm/cfc files using cfeclipse.  At first I thought it was unrelated to cfeclipse but after reporting a bug to the eclipse community they said it's a bug with cfeclipse.  Here is the thread:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=514280

**Comment by bardware** [comment]
How did you install CFEclipse plugin? From what update site? Which version?

`Works on my machine`. Windows, [update-dev](http://cfeclipse.org/update-dev/)

**Comment by tobiashreiter** [comment]
I've had the same experience. Here's the relevant error that I've been receiving (I get the error on neon.2 (4.6.2) and neon.3 (4.6.3):

java.lang.NoClassDefFoundError: org/antlr/runtime/tree/RewriteEmptyStreamException
	at org.cfeclipse.cfml.editors.ICFDocument.setParserResource(ICFDocument.java:264)

My most recent test was using 1.5.3, although 1.5.2 seems to have the same issue. I would revert to 1.5.1, but I can't find that version anywhere (it's not on update-archive).

**Comment by denuno** [comment]
Can y'all give the latest from update-dev a go and see if it works again?  I made some changes for the latest version of cfml.parsing which theoretically fix the missing class error, and should let us run the latest and greatest parser and linter versions.  (Which are fantastic BTW!)

**Comment by bardware** [comment]
[update-dev](http://cfeclipse.org/update-dev/) is still on January, 8th release ;(

**Comment by SteffenMo** [comment]
Thank you denuno, I have re-installed the latest dev-version from http://cfeclipse.org/update-dev/ with "Install New Software" (in Eclipse) and it worked for me.

I had the same error as tobiashreiter above
java.lang.NoClassDefFoundError: org/antlr/runtime/tree/RewriteEmptyStreamException

**Comment by tobiashreiter** [comment]
I was able to get 1.5.2 to work by downloading copies of ANTL v3 and v4 and
installing them in my Eclipse plugins folder.

Can you tell us what changes you made to the current version of CFEclipse
to prevent the NoClassDefFound error?

I'm a bit skittish to change anything about my install right now -- I spent
nearly 8 hours trying to get it to work!

Thanks,
Tiby

**Comment by am2605** [comment]
I think this may have been resolved when CFLint was updated.  Can we close?

**Comment by am2605** [comment]
Closed in the expectation this will be fixed in https://cfeclipse.org/update-nightly and future stable builds
