### ISSUE TITLE
error installing CF801-Extensions-for-Eclipse

### ISSUE THREAD

**Issue by awittenberg** [cfeclipse/cfeclipse#85]
Eclipse Neon, CFEclipse 
I'm trying to get the step debugger. Tried installing from a copy downloaded to my computer. It worked with Juno before I had my computer reimaged.

An error occurred while installing the items
session context was:(profile=C__Program Files_eclipse_javascript-neon_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]com.adobe.coldfusion.fbext_help 1.0.1, action=).
Failed to prepare partial IU: [R]com.adobe.coldfusion.fbext_help 1.0.1.

Also reported to Eclipse Bugzilla

**Comment by denuno** [comment]
CFEclipse doesn't have a step debugger... but if you have your old files you could try dropping those plugins into the new version's plugins folder, bypassing the install error at least.  Closing for now unless a step debugger turns out to be a feature someone added while I wasn't looking. :smiley:
