### ISSUE TITLE
Error in plugin

### ISSUE THREAD

**Issue by bardware** [cfeclipse/cfeclipse#90]
I just saw two weeks ago you updated the dev branch to a new CFParser and CFLint 1.3.
I update my eclipse and open a file with the following content. I had created this file to see the `EXCESSIVE_ARGUMENTS` warning working.
In line 21 in eclipse I see the error icon and the popup reads: `ERROR: Error in plugin (PLUGIN_ERROR) offset 1077 col: 3 line 21 len:5`
This exact error is printed multiple times.
```
<cfcomponent>
	<cffunction name="fkt1" returntype="struct" access="public">
		<cfargument name="arg1" type="string" required="true">
		<cfargument name="arg2" type="string" required="true">
		<cfargument name="arg3" type="string" required="true">
		<cfargument name="arg4" type="string" required="true">
		<cfargument name="arg5" type="string" required="true">
		<cfargument name="arg6" type="string" required="true">
		<cfargument name="arg7" type="string" required="true">
		<cfargument name="arg8" type="string" required="true">
		<cfargument name="arg10" type="string" required="true">
		<cfargument name="arg11" type="string" required="true">
		<cfargument name="arg12" type="string" required="true">
		<cfargument name="arg13" type="string" required="true">
		<cfargument name="arg14" type="string" required="true">
		<cfargument name="arg15" type="string" required="true">
		<cfargument name="arg16" type="string" required="true">
		<cfargument name="arg17" type="string" required="true">
		<cfargument name="arg18" type="string" required="true">

		<cfset local.struRes = {}>




		<cfreturn local.struRes>
	</cffunction>


</cfcomponent>
```

**Comment by denuno** [comment]
Ah, that one I think is from a previous version of the CFLint config conflicting... manual fix would be deleting the cflint config file from the plugin resource dir, which is somewhere in your workspace .metadata folder (search for `cflint.definition.json`) or to specify "store config in project" (context-click on project, select properties, select the CFLint set) which will let you delete it and whatnot.  This will be fixed after the tweaks to how the cflint configs are stored is in.

**Comment by bardware** [comment]
OK; I deleted the file, open the CFLint config dialog, checked "save in project" and the error (other file, same message) vanished.

Thank you!
