### ISSUE TITLE
Cannot perform operation. Computing alternative tasks

### ISSUE THREAD

**Issue by Croseven** [cfeclipse/cfeclipse#93]
Well looks like cfeclipse is down, I cannot install it, I installed the latest Eclipse, when that didn't work I went and installed Eclipse Neon but the same error

Missing requirement: CFEclipse (including MXUnit and Frameworks) 1.5.2.201612262348 (org.cfeclipse.cfml.feature.feature.group 1.5.2.201612262348) requires 'org.mxunit.eclipseplugin.feature.feature.group 1.5.0' but it could not be found

And there is no manual installation available so guess I am screwed
Any Suggestions
![image](https://user-images.githubusercontent.com/22808697/32361303-a0f5deec-c067-11e7-9113-f4576e955e28.png)

**Comment by am2605** [comment]
I think this is because the mxunit domain no longer exists.

@denuno are you able to give us any help with this - can we get rid of the mxunit dependency?  I doubt anyone wants it anymore?
