### ISSUE TITLE
CFStoredproc Code Folding (and other tags)

### ISSUE THREAD

**Issue by mrkeysh** [cfeclipse/cfeclipse#94]
Currently, the CFEclipse project can only support 8 "tags" to fold, plus CFML Comments and HTML Comments.  There is no ability to add more tags to this folding, though they can be edited.  
The initial 8 are....
      cffunction
     cfquery
     cfscript
     cfloop
     cfscript
     cfif
     cfswitch
     cfcase
First, I am not sure why CFScript is listed twice in the default list, but that is easy to replace.
I need these 8 listed PLUS more, such as CFStoredproc, cftry, cfcatch, cfcomponent, cfsavedcontent, cfsilent, cflock, cfoutput, cfelse, cfelseif, cfthrow, cffinally, plus possibly some HTML tags such as div , span, form, body, html, style, script, select, or even some html5 tags like footer, header, article, main, nav, section, details, summary, aside  or even some lesser used ColdFusion tags
In any of those 4 categories (HTML tags, HTML5 tags, ColdFusion tags, lesser used CF tags) that I just rambled off the top of my head there is 8 or more and in order to use even 1 of those alternatives would be to replace one of the existing 8 and give it priority over those initial 8 because its limited to only 8.  Removing 1 of those 8 could make others useless (ie - cfcase or cfswitch).  
Can there be a file or setting to add more to this list?  There is already an option to "disable" that tag which is almost useless if you are limited to only 8 and can't add or remove (only change) from that at all.

**Comment by denuno** [comment]
This is in dev and will be in the next release, so I'm going to go ahead and close this, so it'll show up in the release notes.

**Comment by denuno** [comment]
Thanks for adding these!  If you want to open a new ticket to "improve code folding preference page", maybe with what would be a nice UI, that'd be cool.  We for sure want to make it dynamic, maybe just lists with + and - and free-form text entry (though auto-lookup of tags/functions would be slick).
