### ISSUE TITLE
Editor could not be initialized, UnsupportedClassVersionError on Windows 10, Java 1.7.0_67

### ISSUE THREAD

**Issue by jwdvorak** [cfeclipse/cfeclipse#97]
Using Windows 10 (x64), Java 1.7.0_67 (x64), Eclipse Mars (4.5 x64, Java EE), CFEclipse 1.5.2... cannot open *.cfm files, error message is 'Editor could not be initialized.'  Exception stack trace is java.lang.UnsupportedClassVersionError: cfml/parsing/ParseMessage : Unsupported major.minor version 52.0.

Have uninstalled/reinstalled plugin, installed on clean Eclipse instance, error is consistent.  Would upgrade to newer versions of Java / Eclipse if possible, but backward compatibility with legacy dev tools (Adobe Flex 4.7) and test/production app server(s) configuration (Java 1.7.0_67) negate that option.  Have not (yet) tried on another Win10 computer to see if issue is reproducible; issue is not present on older Windows 7 machine(s) with same configuration (Java 1.7.0_67, Eclipse Mars 4.5 EE).

**Comment by denuno** [comment]
The newest versions of the parser and linter leverage use and rely on libraries that use the performance enhancing features only available in java 8+, so sadly there's not much to do but stick with an older version if you can't update the JRE.  Will the Flex plugin just not run with a newer java version?

**Comment by jwdvorak** [comment]
Yes, sort of...  Flex 4.7 plugin was only supported up to Eclipse Indigo; a common hack was to install multiple versions of Eclipse (Indigo, plus desired version), install the plugin to Indigo, drag and drop the folder / files  created into newer (unsupported) version of Eclipse.  That hack still seems to work with Eclipse Mars, but the bigger issue was the jump from Java 7 to 8.  Ultimately, that's the direction I'm moving, so this (CFEclipse) issue will become moot.  Thanks for response...

**Comment by denuno** [comment]
If it's just the Flex update site/install not working, it could maybe be run through a Tycho update site build thing (what we use to generate the update sites), which would at least spit out a valid update site for the newer versions of Eclipse.  Take the jump to 8 sayeth I!  The performance improvements are worth it-- plus I think 9 is out now, and 10 is already on the way. :smiley:

**Comment by denuno** [comment]
Closing this for now, workaround is to use the older version ~1.5.1, newer versions require Java 8.
