### ISSUE TITLE
closing tag does not match current parent

### ISSUE THREAD

**Issue by bardware** [cfeclipse/cfeclipse#99]
Hi,

my test file is very short:
```
<cfcomponent>

	<cffunction name="myfunc" returntype="struct">
		<cfargument name="arg1">

		<cfset local.struResult = {}>


		<cfreturn local.struResult>
	</cffunction>

</cfcomponent>
```

The line with the closing `cfcomponent` is marked with an infomation icon reading `Closing tag </cfcomponent> does not match the current parent item cffunction`
![image](https://user-images.githubusercontent.com/802702/34655016-07a58230-f404-11e7-9615-1c7e324e1b88.png)

Where does that come from?

**Comment by denuno** [comment]
Is this with org.cfeclipse.cfparser 2.6.0 (help > about eclipse > installation details > plug-ins)?  I'm not able to reproduce using the latest dev CFEclipse (1.5.3) and latest stable cfparser (2.6.0).  Maybe try restarting eclipse with `-clean`?

**Comment by bardware** [comment]
It says cfparser 2.6.0.
I copied my code snippet to a fresh file and the message is gone. Maybe this information is cached somewhere.

**Comment by denuno** [comment]
You should be able to click on the problem in the `Problems` view and just delete it -- and then re-save the file -- and if it comes back after the save it's a fresh parse error.
